// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MobileBackend.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MobileBackend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221030145852_Elig")]
    partial class Elig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("loanflow")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MobileBackend.Models.Applicant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<int>("AddlIncome")
                        .HasColumnType("integer");

                    b.Property<string>("Address_Line1")
                        .HasColumnType("text");

                    b.Property<string>("Address_Line2")
                        .HasColumnType("text");

                    b.Property<string>("Adhaar_No")
                        .HasColumnType("text");

                    b.Property<string>("Applicant_First_Name")
                        .HasColumnType("text");

                    b.Property<string>("Applicant_Last_Name")
                        .HasColumnType("text");

                    b.Property<string>("Applicant_Middle_Name")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Caste")
                        .HasColumnType("text");

                    b.Property<string>("City_Village")
                        .HasColumnType("text");

                    b.Property<string>("Date_Of_Birth")
                        .HasColumnType("text");

                    b.Property<string>("Dependent")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("DocumentExecution")
                        .HasColumnType("text");

                    b.Property<string>("Driving_Lic")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<string>("ElectionId")
                        .HasColumnType("text");

                    b.Property<string>("ExistingCIF")
                        .HasColumnType("text");

                    b.Property<int>("GMI")
                        .HasColumnType("integer");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<string>("Guardian_Name")
                        .HasColumnType("text");

                    b.Property<string>("KYC_Upload")
                        .HasColumnType("text");

                    b.Property<string>("LatestIncome")
                        .HasColumnType("text");

                    b.Property<string>("MaritialStatus")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<int>("NMI")
                        .HasColumnType("integer");

                    b.Property<string>("NetWorth")
                        .HasColumnType("text");

                    b.Property<string>("Occupation")
                        .HasColumnType("text");

                    b.Property<string>("PAN_No")
                        .HasColumnType("text");

                    b.Property<string>("PINCode")
                        .HasColumnType("text");

                    b.Property<string>("Passport")
                        .HasColumnType("text");

                    b.Property<string>("PermanentAddress")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBankingRelation")
                        .HasColumnType("text");

                    b.Property<string>("RelationWithAppl")
                        .HasColumnType("text");

                    b.Property<string>("Relationship")
                        .HasColumnType("text");

                    b.Property<string>("Religion")
                        .HasColumnType("text");

                    b.Property<string>("RemarkOnAddlIncome")
                        .HasColumnType("text");

                    b.Property<string>("RemarkOnNMI")
                        .HasColumnType("text");

                    b.Property<string>("RemarkOther")
                        .HasColumnType("text");

                    b.Property<string>("Salutation")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<string>("TypeofApplicant")
                        .HasColumnType("text");

                    b.Property<string>("Voter_Id")
                        .HasColumnType("text");

                    b.Property<string>("WorkPlace")
                        .HasColumnType("text");

                    b.Property<string>("WorkPlaceAddress")
                        .HasColumnType("text");

                    b.Property<string>("WorkingSince")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("MobileBackend.Models.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("ApplicantShortName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("AppliedAmt")
                        .HasColumnType("numeric");

                    b.Property<string>("BranchId")
                        .HasColumnType("text");

                    b.Property<string>("ControlRemark")
                        .HasColumnType("text");

                    b.Property<string>("ControlStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ControlledDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Eligibility")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("ForwardedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InspectionAllotedTo")
                        .HasColumnType("text");

                    b.Property<DateTime?>("InspectionAllotmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InspectionDone")
                        .HasColumnType("text");

                    b.Property<bool>("IsLead")
                        .HasColumnType("boolean");

                    b.Property<string>("LeadSourceAgency")
                        .HasColumnType("text");

                    b.Property<string>("LeadSourcedBy")
                        .HasColumnType("text");

                    b.Property<string>("LeadStage")
                        .HasColumnType("text");

                    b.Property<string>("LoanScheme")
                        .HasColumnType("text");

                    b.Property<string>("MappedCCAccount")
                        .HasColumnType("text");

                    b.Property<string>("MappedTLAccount")
                        .HasColumnType("text");

                    b.Property<string>("Owner")
                        .HasColumnType("text");

                    b.Property<string>("OwnerUser")
                        .HasColumnType("text");

                    b.Property<string>("PendingAction")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("ROIType")
                        .HasColumnType("text");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("SanctionedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SanctionedLevel")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SendToControlDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SponsoringAgency")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<decimal>("SubsidyAmt")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeOfApplicant")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("MobileBackend.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("BranchId")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("text");

                    b.Property<string>("FCMId")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.Property<string>("OtherRole")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Scale")
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("character varying(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("MobileBackend.Models.Branch", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AMHCode")
                        .HasColumnType("text");

                    b.Property<string>("BrType")
                        .HasColumnType("text");

                    b.Property<string>("BranchName")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("RegionalOffice")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("MobileBackend.Models.BranchPerformance", b =>
                {
                    b.Property<string>("BranchCode")
                        .HasColumnType("text");

                    b.Property<float>("AdvanceLastDay")
                        .HasColumnType("real");

                    b.Property<float>("AdvanceLastFy")
                        .HasColumnType("real");

                    b.Property<float>("AdvanceLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("AdvanceLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("AdvancePrevFy")
                        .HasColumnType("real");

                    b.Property<float>("AgriLastDay")
                        .HasColumnType("real");

                    b.Property<float>("AgriLastFy")
                        .HasColumnType("real");

                    b.Property<float>("AgriLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("AgriLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("AgriPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("CASALastDay")
                        .HasColumnType("real");

                    b.Property<float>("CASALastFy")
                        .HasColumnType("real");

                    b.Property<float>("CASALastMonth")
                        .HasColumnType("real");

                    b.Property<float>("CASALastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("CASAPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("CarLastDay")
                        .HasColumnType("real");

                    b.Property<float>("CarLastFy")
                        .HasColumnType("real");

                    b.Property<float>("CarLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("CarLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("CarPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("DepositLastDay")
                        .HasColumnType("real");

                    b.Property<float>("DepositLastFy")
                        .HasColumnType("real");

                    b.Property<float>("DepositLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("DepositLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("DepositPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("GoldLastDay")
                        .HasColumnType("real");

                    b.Property<float>("GoldLastFy")
                        .HasColumnType("real");

                    b.Property<float>("GoldLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("GoldLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("GoldPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("HLLastDay")
                        .HasColumnType("real");

                    b.Property<float>("HLLastFy")
                        .HasColumnType("real");

                    b.Property<float>("HLLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("HLLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("HLPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("KCCLastDay")
                        .HasColumnType("real");

                    b.Property<float>("KCCLastFy")
                        .HasColumnType("real");

                    b.Property<float>("KCCLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("KCCLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("KCCPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("NPALastDay")
                        .HasColumnType("real");

                    b.Property<float>("NPALastFy")
                        .HasColumnType("real");

                    b.Property<float>("NPALastMonth")
                        .HasColumnType("real");

                    b.Property<float>("NPALastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("NPAPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("NRLMLastDay")
                        .HasColumnType("real");

                    b.Property<float>("NRLMLastFy")
                        .HasColumnType("real");

                    b.Property<float>("NRLMLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("NRLMLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("NRLMPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("PLLastDay")
                        .HasColumnType("real");

                    b.Property<float>("PLLastFy")
                        .HasColumnType("real");

                    b.Property<float>("PLLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("PLLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("PLPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("PerLastDay")
                        .HasColumnType("real");

                    b.Property<float>("PerLastFy")
                        .HasColumnType("real");

                    b.Property<float>("PerLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("PerLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("PerPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("SMELLastDay")
                        .HasColumnType("real");

                    b.Property<float>("SMELLastFy")
                        .HasColumnType("real");

                    b.Property<float>("SMELLastMonth")
                        .HasColumnType("real");

                    b.Property<float>("SMELLastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("SMELPrevFy")
                        .HasColumnType("real");

                    b.Property<float>("SMELastDay")
                        .HasColumnType("real");

                    b.Property<float>("SMELastFy")
                        .HasColumnType("real");

                    b.Property<float>("SMELastMonth")
                        .HasColumnType("real");

                    b.Property<float>("SMELastQuarter")
                        .HasColumnType("real");

                    b.Property<float>("SMEPrevFy")
                        .HasColumnType("real");

                    b.HasKey("BranchCode");

                    b.ToTable("BranchPerformances");
                });

            modelBuilder.Entity("MobileBackend.Models.CIBILLoanInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CIBILRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("EMIConsidered")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeResponse")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("accountType")
                        .HasColumnType("text");

                    b.Property<string>("amountOverdue")
                        .HasColumnType("text");

                    b.Property<string>("cibilRemarksCode")
                        .HasColumnType("text");

                    b.Property<string>("cibilRemarksDate")
                        .HasColumnType("text");

                    b.Property<string>("collateralType")
                        .HasColumnType("text");

                    b.Property<string>("creditLimit")
                        .HasColumnType("text");

                    b.Property<string>("currentBalance")
                        .HasColumnType("text");

                    b.Property<string>("dateClosed")
                        .HasColumnType("text");

                    b.Property<string>("dateOpened")
                        .HasColumnType("text");

                    b.Property<string>("dateReported")
                        .HasColumnType("text");

                    b.Property<string>("errorCode")
                        .HasColumnType("text");

                    b.Property<string>("errorRemarksCode1")
                        .HasColumnType("text");

                    b.Property<string>("errorRemarksCode2")
                        .HasColumnType("text");

                    b.Property<string>("highCreditAmount")
                        .HasColumnType("text");

                    b.Property<string>("index")
                        .HasColumnType("text");

                    b.Property<string>("lastPaymentDate")
                        .HasColumnType("text");

                    b.Property<string>("memberShortName")
                        .HasColumnType("text");

                    b.Property<string>("ownershipIndicator")
                        .HasColumnType("text");

                    b.Property<string>("paymentEndDate")
                        .HasColumnType("text");

                    b.Property<string>("paymentHistory")
                        .HasColumnType("text");

                    b.Property<string>("paymentStartDate")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CIBILRequestId");

                    b.ToTable("CIBILLoanInfo");
                });

            modelBuilder.Entity("MobileBackend.Models.CIBILRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicantId")
                        .HasColumnType("integer");

                    b.Property<string>("CiibilControlNumber")
                        .HasColumnType("text");

                    b.Property<string>("RequestDate")
                        .HasColumnType("text");

                    b.Property<string>("ResponseFileName")
                        .HasColumnType("text");

                    b.Property<string>("Score1")
                        .HasColumnType("text");

                    b.Property<string>("Score2")
                        .HasColumnType("text");

                    b.Property<string>("Score3")
                        .HasColumnType("text");

                    b.Property<string>("ScoreName1")
                        .HasColumnType("text");

                    b.Property<string>("ScoreName2")
                        .HasColumnType("text");

                    b.Property<string>("ScoreName3")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.ToTable("CIBILRequests");
                });

            modelBuilder.Entity("MobileBackend.Models.CSPVisit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CSPId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ClosureOfficialId")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeMasterId")
                        .HasColumnType("text");

                    b.Property<string>("Location_lat")
                        .HasColumnType("text");

                    b.Property<string>("Location_long")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SystemLogDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VisitRemarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CSPId");

                    b.HasIndex("EmployeeMasterId");

                    b.ToTable("CSPVisits");
                });

            modelBuilder.Entity("MobileBackend.Models.Charge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("Frequency")
                        .HasColumnType("text");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Charges");
                });

            modelBuilder.Entity("MobileBackend.Models.CibilEnquiry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CIBILRequestId")
                        .HasColumnType("integer");

                    b.Property<string>("enquiryAmount")
                        .HasColumnType("text");

                    b.Property<string>("enquiryDate")
                        .HasColumnType("text");

                    b.Property<string>("enquiryPurpose")
                        .HasColumnType("text");

                    b.Property<string>("index")
                        .HasColumnType("text");

                    b.Property<string>("memberShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CIBILRequestId");

                    b.ToTable("CibilEnquiries");
                });

            modelBuilder.Entity("MobileBackend.Models.ControlInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AppliedAmt")
                        .HasColumnType("numeric");

                    b.Property<int>("EligibleAmt")
                        .HasColumnType("integer");

                    b.Property<string>("ReceivedDocuments")
                        .HasColumnType("text");

                    b.Property<decimal>("SanctionedCC")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SanctionedTL")
                        .HasColumnType("numeric");

                    b.Property<string>("Statement1")
                        .HasColumnType("text");

                    b.Property<string>("Statement10")
                        .HasColumnType("text");

                    b.Property<string>("Statement11")
                        .HasColumnType("text");

                    b.Property<string>("Statement12")
                        .HasColumnType("text");

                    b.Property<string>("Statement13")
                        .HasColumnType("text");

                    b.Property<string>("Statement14")
                        .HasColumnType("text");

                    b.Property<string>("Statement15")
                        .HasColumnType("text");

                    b.Property<string>("Statement16")
                        .HasColumnType("text");

                    b.Property<string>("Statement17")
                        .HasColumnType("text");

                    b.Property<string>("Statement2")
                        .HasColumnType("text");

                    b.Property<string>("Statement3")
                        .HasColumnType("text");

                    b.Property<string>("Statement4")
                        .HasColumnType("text");

                    b.Property<string>("Statement5")
                        .HasColumnType("text");

                    b.Property<string>("Statement6")
                        .HasColumnType("text");

                    b.Property<string>("Statement7")
                        .HasColumnType("text");

                    b.Property<string>("Statement8")
                        .HasColumnType("text");

                    b.Property<string>("Statement9")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.ToTable("ControlInformation");
                });

            modelBuilder.Entity("MobileBackend.Models.Csp", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BranchMasterId")
                        .HasColumnType("text");

                    b.Property<string>("CSPName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorporateAgency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("BranchMasterId");

                    b.ToTable("Csps");
                });

            modelBuilder.Entity("MobileBackend.Models.Disbursement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("BankPart")
                        .HasColumnType("numeric");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Disbursements");
                });

            modelBuilder.Entity("MobileBackend.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("MobileBackend.Models.KCCCropDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Crop")
                        .HasColumnType("text");

                    b.Property<string>("CropInsurance")
                        .HasColumnType("text");

                    b.Property<decimal>("IrrigatedArea")
                        .HasColumnType("numeric");

                    b.Property<int>("KCCLandDetailId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SOFIrrigatedArea")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SOFUnIrrigatedArea")
                        .HasColumnType("numeric");

                    b.Property<string>("Season")
                        .HasColumnType("text");

                    b.Property<decimal>("UnIrrigatedArea")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("KCCLandDetailId");

                    b.ToTable("KCCCropDetails");
                });

            modelBuilder.Entity("MobileBackend.Models.KCCLandDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Charge")
                        .HasColumnType("text");

                    b.Property<string>("DharanAdhikar")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<decimal>("IrrigatedArea")
                        .HasColumnType("numeric");

                    b.Property<string>("KhasraNo")
                        .HasColumnType("text");

                    b.Property<decimal>("NonAgriArea")
                        .HasColumnType("numeric");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .HasColumnType("text");

                    b.Property<string>("RI")
                        .HasColumnType("text");

                    b.Property<string>("RajaswaNyayalay")
                        .HasColumnType("text");

                    b.Property<string>("SourceofIrrigation")
                        .HasColumnType("text");

                    b.Property<string>("Tehsil")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalArea")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnIrrigatedArea")
                        .HasColumnType("numeric");

                    b.Property<string>("Village")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("KCCLandDetails");
                });

            modelBuilder.Entity("MobileBackend.Models.LeadRoadMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Attachement")
                        .HasColumnType("text");

                    b.Property<string>("EntryType")
                        .HasColumnType("text");

                    b.Property<int?>("LeadDetailsId")
                        .HasColumnType("integer");

                    b.Property<int>("LeadId")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LeadDetailsId");

                    b.ToTable("LeadComments");
                });

            modelBuilder.Entity("MobileBackend.Models.Leads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AadhaarNo")
                        .HasColumnType("text");

                    b.Property<string>("AddressLine1")
                        .HasColumnType("text");

                    b.Property<string>("ApplicantName")
                        .HasColumnType("text");

                    b.Property<int>("AppliedAmt")
                        .HasColumnType("integer");

                    b.Property<string>("BranchId")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<DateTime>("DOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DetailsofEarningMember")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElectionId")
                        .HasColumnType("text");

                    b.Property<bool>("ExistingCustomer")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LeadDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LeadStatus")
                        .HasColumnType("text");

                    b.Property<string>("MobileNumber")
                        .HasColumnType("text");

                    b.Property<string>("OtherEarningMember")
                        .HasColumnType("text");

                    b.Property<string>("OtherIncomeSource")
                        .HasColumnType("text");

                    b.Property<string>("PANNo")
                        .HasColumnType("text");

                    b.Property<string>("PinCode")
                        .HasColumnType("text");

                    b.Property<string>("PrimaryBank")
                        .HasColumnType("text");

                    b.Property<string>("SourcedBy")
                        .HasColumnType("text");

                    b.Property<string>("SourcingAgency")
                        .HasColumnType("text");

                    b.Property<string>("UploadAadhaar")
                        .HasColumnType("text");

                    b.Property<string>("UploadDocument1")
                        .HasColumnType("text");

                    b.Property<string>("UploadDocument2")
                        .HasColumnType("text");

                    b.Property<string>("UploadElectionId")
                        .HasColumnType("text");

                    b.Property<string>("UploadPAN")
                        .HasColumnType("text");

                    b.Property<string>("UploadPhoto")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Leads");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Leads");
                });

            modelBuilder.Entity("MobileBackend.Models.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AppliedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("LoanAccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Moratorium")
                        .HasColumnType("text");

                    b.Property<decimal>("PLR")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RateOfInterest")
                        .HasColumnType("numeric");

                    b.Property<string>("RenewalDate")
                        .HasColumnType("text");

                    b.Property<string>("RepayStartDate")
                        .HasColumnType("text");

                    b.Property<decimal>("RepayTerm")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Repayment")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SanctionedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Spread")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeOfFacility")
                        .HasColumnType("text");

                    b.Property<string>("UtilizationPeriod")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("LoanApplications");
                });

            modelBuilder.Entity("MobileBackend.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MobileBackend.Models.PreInspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ClosureDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ClosureOfficialId")
                        .HasColumnType("text");

                    b.Property<string>("EmployeeMasterId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SystemLogDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VisitRemarks")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EmployeeMasterId");

                    b.ToTable("PreInspection");
                });

            modelBuilder.Entity("MobileBackend.Models.PreValueStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PreInspectionValueStatements");
                });

            modelBuilder.Entity("MobileBackend.Models.PreVisitRemark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("RemarksVerifyingOfficial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemarksVisitingOfficial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ValueStatementId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PreIsnpectionRemarks");
                });

            modelBuilder.Entity("MobileBackend.Models.ProjectCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("AppliedAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EligibleForLoan")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("ProjectCosts");
                });

            modelBuilder.Entity("MobileBackend.Models.Remark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("DataType")
                        .HasColumnType("text");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("EmpName")
                        .HasColumnType("text");

                    b.Property<string>("SpecialRemark")
                        .HasColumnType("text");

                    b.Property<string>("Statment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TypeOfRecomendation")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfRemark")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Remarks");
                });

            modelBuilder.Entity("MobileBackend.Models.Security", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer");

                    b.Property<string>("Boundary")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("DocumentDetails")
                        .HasColumnType("numeric");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("PlotNo")
                        .HasColumnType("text");

                    b.Property<decimal>("RateOfInterest")
                        .HasColumnType("numeric");

                    b.Property<string>("TypeOfCharge")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfSecurity")
                        .HasColumnType("text");

                    b.Property<decimal>("Valuation")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("MobileBackend.Models.ValueStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("InputType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CSPValueStatements");
                });

            modelBuilder.Entity("MobileBackend.Models.VisitRemark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("RemarksVerifyingOfficial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RemarksVisitingOfficial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ValueStatementId")
                        .HasColumnType("integer");

                    b.Property<int>("VisitId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("VisitRemarks");
                });

            modelBuilder.Entity("MobileBackend.Models.GoldLoanLeads", b =>
                {
                    b.HasBaseType("MobileBackend.Models.Leads");

                    b.Property<string>("AnyOtherLoan")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("GoldLoanLeads");
                });

            modelBuilder.Entity("MobileBackend.Models.KCCLeads", b =>
                {
                    b.HasBaseType("MobileBackend.Models.Leads");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<string>("IrrigationSource")
                        .HasColumnType("text");

                    b.Property<string>("KhasraNo")
                        .HasColumnType("text");

                    b.Property<string>("RI")
                        .HasColumnType("text");

                    b.Property<string>("Tehsil")
                        .HasColumnType("text");

                    b.Property<string>("Village")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("KCCLeads");
                });

            modelBuilder.Entity("MobileBackend.Models.TPLLeads", b =>
                {
                    b.HasBaseType("MobileBackend.Models.Leads");

                    b.Property<string>("Make")
                        .HasColumnType("text");

                    b.Property<string>("PastExperience")
                        .HasColumnType("text");

                    b.Property<string>("TypeOfVehichle")
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("TPLLeads");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MobileBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MobileBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MobileBackend.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.Applicant", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", null)
                        .WithMany("Applicants")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.Application", b =>
                {
                    b.HasOne("MobileBackend.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");
                });

            modelBuilder.Entity("MobileBackend.Models.ApplicationUser", b =>
                {
                    b.HasOne("MobileBackend.Models.Branch", "BranchDetails")
                        .WithMany()
                        .HasForeignKey("BranchId");
                });

            modelBuilder.Entity("MobileBackend.Models.CIBILLoanInfo", b =>
                {
                    b.HasOne("MobileBackend.Models.CIBILRequest", "CIBILRequestDetail")
                        .WithMany("CibilLoans")
                        .HasForeignKey("CIBILRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.CIBILRequest", b =>
                {
                    b.HasOne("MobileBackend.Models.Applicant", "ApplicantDetail")
                        .WithMany("CibilRequests")
                        .HasForeignKey("ApplicantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.CSPVisit", b =>
                {
                    b.HasOne("MobileBackend.Models.Csp", "Csp")
                        .WithMany()
                        .HasForeignKey("CSPId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileBackend.Models.ApplicationUser", "EmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmployeeMasterId");
                });

            modelBuilder.Entity("MobileBackend.Models.Charge", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("Charges")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.CibilEnquiry", b =>
                {
                    b.HasOne("MobileBackend.Models.CIBILRequest", "CIBILRequestDetail")
                        .WithMany()
                        .HasForeignKey("CIBILRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.ControlInformation", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithOne("ControlInformations")
                        .HasForeignKey("MobileBackend.Models.ControlInformation", "ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.Csp", b =>
                {
                    b.HasOne("MobileBackend.Models.Branch", "BranchMaster")
                        .WithMany()
                        .HasForeignKey("BranchMasterId");
                });

            modelBuilder.Entity("MobileBackend.Models.Disbursement", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("Disbursements")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.Document", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("Documents")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.KCCCropDetail", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("KCCCropDetails")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileBackend.Models.KCCLandDetail", "KCCLandDetails")
                        .WithMany()
                        .HasForeignKey("KCCLandDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.KCCLandDetail", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("KCCLandDetails")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.LeadRoadMap", b =>
                {
                    b.HasOne("MobileBackend.Models.Leads", "LeadDetails")
                        .WithMany("Comments")
                        .HasForeignKey("LeadDetailsId");
                });

            modelBuilder.Entity("MobileBackend.Models.Leads", b =>
                {
                    b.HasOne("MobileBackend.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");
                });

            modelBuilder.Entity("MobileBackend.Models.LoanApplication", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("LoanApplications")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.Log", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", null)
                        .WithMany("Logs")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.PreInspection", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", null)
                        .WithMany("Inspections")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MobileBackend.Models.ApplicationUser", "EmployeeMaster")
                        .WithMany()
                        .HasForeignKey("EmployeeMasterId");
                });

            modelBuilder.Entity("MobileBackend.Models.ProjectCost", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("ProjectCost")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.Remark", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", null)
                        .WithMany("Remarks")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MobileBackend.Models.Security", b =>
                {
                    b.HasOne("MobileBackend.Models.Application", "ApplicationDetail")
                        .WithMany("Securities")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
